name: BingoPlg
version: '1.0'
main: me.dubovoy.bingoPlg.BingoPlg
api-version: '1.21'
authors: [ Dubovoy6211@gmail.com ]

commands:
  heal:
    description: "Heals player"
    aliases: [ h ]
    permissions: bingoPlg.heal
    usage: "/heal"

  createteam:
    description: ""
    aliases: [ crtm ]
    usage: "/createteam"

  deleteteam:
    description: ""
    aliases: [ dltm ]
    usage: "/deleteteam"

  jointeam:
    description: ""
    aliases: [ jt, join ]
    usage: "/jointeam"

  teleportteam:
    description: ""
    aliases: [ tpt, tptm]
    usage: "/teleportteam"

  table:
    description: ""
    aliases: [ ]
    usage: "/table 0"

  createtable:
    description: ""
    aliases: [ crtb ]
    usage: "/createtable"

  StartBingo:
    description: ""
    aliases: [ sb ]
    usage: "/StartBingo"

  permissions:
    bingoPlg.*:
      description: Gives access to all doorman commands
      children:
        bingoPlg.heal: op
#        bingoPlg.ban: true
#        bingoPlg.knock: true
#        bingoPlg.denied: false
    bingoPlg.heal:
      description: "Право для использования команды /heal"
      default: op