package me.dubovoy.bingoPlg.logic;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.google.gson.stream.JsonReader;
import org.bukkit.Material;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.List;

public class Difficulty{

    public static List<Material> DiffZero(){
        List<Material> materials = new ArrayList<>();
        materials.add(Material.ANDESITE);
        materials.add(Material.ANDESITE_SLAB);
        materials.add(Material.ANDESITE_STAIRS);
        materials.add(Material.ANDESITE_WALL);
        materials.add(Material.BAKED_POTATO);
        materials.add(Material.BIRCH_BOAT);
        materials.add(Material.BIRCH_BUTTON);
        materials.add(Material.BIRCH_DOOR);
        materials.add(Material.BIRCH_FENCE);
        materials.add(Material.BIRCH_FENCE_GATE);
        materials.add(Material.BIRCH_LOG);
        materials.add(Material.BIRCH_PLANKS);
        materials.add(Material.BIRCH_PRESSURE_PLATE);
        materials.add(Material.BIRCH_SIGN);
        materials.add(Material.BIRCH_SLAB);
        materials.add(Material.BIRCH_STAIRS);
        materials.add(Material.BIRCH_TRAPDOOR);
        materials.add(Material.BIRCH_WOOD);
        materials.add(Material.BOWL);
        materials.add(Material.CAMPFIRE);
        materials.add(Material.CHEST);
        materials.add(Material.COAL);
        materials.add(Material.COAL_BLOCK);
        materials.add(Material.COBBLESTONE);
        materials.add(Material.COBBLESTONE_SLAB);
        materials.add(Material.COBBLESTONE_STAIRS);
        materials.add(Material.COBBLESTONE_WALL);
        materials.add(Material.COMPOSTER);
        materials.add(Material.CRAFTING_TABLE);
        materials.add(Material.DARK_OAK_BOAT);
        materials.add(Material.DARK_OAK_BUTTON);
        materials.add(Material.DARK_OAK_DOOR);
        materials.add(Material.DARK_OAK_FENCE);
        materials.add(Material.DARK_OAK_FENCE_GATE);
        materials.add(Material.DARK_OAK_LOG);
        materials.add(Material.DARK_OAK_PLANKS);
        materials.add(Material.DARK_OAK_PRESSURE_PLATE);
        materials.add(Material.DARK_OAK_SAPLING);
        materials.add(Material.DARK_OAK_SIGN);
        materials.add(Material.DARK_OAK_SLAB);
        materials.add(Material.DARK_OAK_STAIRS);
        materials.add(Material.DARK_OAK_TRAPDOOR);
        materials.add(Material.DARK_OAK_WOOD);
        materials.add(Material.DIORITE);
        materials.add(Material.DIORITE_SLAB);
        materials.add(Material.DIORITE_STAIRS);
        materials.add(Material.DIORITE_WALL);
        materials.add(Material.DIRT);
        materials.add(Material.DRIED_KELP);
        materials.add(Material.FEATHER);
        materials.add(Material.FLINT);
        materials.add(Material.INK_SAC);
        materials.add(Material.KELP);
        materials.add(Material.LADDER);
        materials.add(Material.LEVER);
        materials.add(Material.MANGROVE_BOAT);
        materials.add(Material.MANGROVE_BUTTON);
        materials.add(Material.MANGROVE_DOOR);
        materials.add(Material.MANGROVE_FENCE);
        materials.add(Material.MANGROVE_FENCE_GATE);
        materials.add(Material.MANGROVE_LOG);
        materials.add(Material.MANGROVE_PLANKS);
        materials.add(Material.MANGROVE_PRESSURE_PLATE);
        materials.add(Material.MANGROVE_PROPAGULE);
        materials.add(Material.MANGROVE_SIGN);
        materials.add(Material.MANGROVE_SLAB);
        materials.add(Material.MANGROVE_STAIRS);
        materials.add(Material.MANGROVE_TRAPDOOR);
        materials.add(Material.MANGROVE_WOOD);
        materials.add(Material.MUD);
        materials.add(Material.MUD_BRICK_SLAB);
        materials.add(Material.MUD_BRICK_STAIRS);
        materials.add(Material.MUD_BRICK_WALL);
        materials.add(Material.MUD_BRICKS);
        materials.add(Material.MUDDY_MANGROVE_ROOTS);
        materials.add(Material.OAK_BOAT);
        materials.add(Material.OAK_BUTTON);
        materials.add(Material.OAK_DOOR);
        materials.add(Material.OAK_FENCE);
        materials.add(Material.OAK_FENCE_GATE);
        materials.add(Material.OAK_LOG);
        materials.add(Material.OAK_PLANKS);
        materials.add(Material.OAK_PRESSURE_PLATE);
        materials.add(Material.OAK_SAPLING);
        materials.add(Material.OAK_SIGN);
        materials.add(Material.OAK_SLAB);
        materials.add(Material.OAK_STAIRS);
        materials.add(Material.OAK_TRAPDOOR);
        materials.add(Material.OAK_WOOD);
        materials.add(Material.ORANGE_DYE);
        materials.add(Material.OXEYE_DAISY);
        materials.add(Material.PETRIFIED_OAK_SLAB);
        materials.add(Material.POPPY);
        materials.add(Material.PORKCHOP);
        materials.add(Material.RED_DYE);
        materials.add(Material.SAND);
        materials.add(Material.SANDSTONE);
        materials.add(Material.SANDSTONE_SLAB);
        materials.add(Material.SANDSTONE_STAIRS);
        materials.add(Material.SANDSTONE_WALL);
        materials.add(Material.SPRUCE_BOAT);
        materials.add(Material.SPRUCE_BUTTON);
        materials.add(Material.SPRUCE_DOOR);
        materials.add(Material.SPRUCE_FENCE);
        materials.add(Material.SPRUCE_FENCE_GATE);
        materials.add(Material.SPRUCE_LOG);
        materials.add(Material.SPRUCE_PLANKS);
        materials.add(Material.SPRUCE_PRESSURE_PLATE);
        materials.add(Material.SPRUCE_SAPLING);
        materials.add(Material.SPRUCE_SIGN);
        materials.add(Material.SPRUCE_SLAB);
        materials.add(Material.SPRUCE_STAIRS);
        materials.add(Material.SPRUCE_TRAPDOOR);
        materials.add(Material.SPRUCE_WOOD);
        materials.add(Material.STICK);
        materials.add(Material.STONE_AXE);
        materials.add(Material.STONE_HOE);
        materials.add(Material.STONE_PICKAXE);
        materials.add(Material.STONE_SHOVEL);
        materials.add(Material.STONE_SWORD);
        materials.add(Material.STRIPPED_DARK_OAK_LOG);
        materials.add(Material.STRIPPED_DARK_OAK_WOOD);
        materials.add(Material.STRIPPED_OAK_LOG);
        materials.add(Material.STRIPPED_OAK_WOOD);
        materials.add(Material.STRIPPED_SPRUCE_LOG);
        materials.add(Material.STRIPPED_SPRUCE_WOOD);
        materials.add(Material.TRAPPED_CHEST);
        materials.add(Material.WHEAT_SEEDS);
        materials.add(Material.WOODEN_AXE);
        materials.add(Material.WOODEN_HOE);
        materials.add(Material.WOODEN_PICKAXE);
        materials.add(Material.WOODEN_SHOVEL);
        materials.add(Material.WOODEN_SWORD);
        materials.add(Material.YELLOW_DYE);
        return materials;
    }

}
