name: BingoPlg
version: '1.4'
main: me.dubovoy.bingoPlg.BingoPlg
api-version: '1.21'
authors: [ Dubovoy6211@gmail.com ]

commands:
  CreateGroup:
    description: ""
    aliases: [ crtm ]
    usage: "/CreateGroup <Название вашей команды>"

  DeleteGroup:
    description: ""
    aliases: [ dltm ]
    permissions: bingoPlg.delete_Group
    usage: "/DeleteGroup <Название команды>"

  JoinGroup:
    description: ""
    aliases: [ jt, join ]
    usage: "/JoinGroup <Название вашей команды>"

  TeleportGroup:
    description: ""
    aliases: [ tptm ]
    permissions: bingoPlg.teleport_Group
    usage: "/TeleportGroup <Название команды>"

  Table:
    description: ""
    aliases: [ ]
    permissions: bingoPlg.table
    usage: "/Table 0"

  CreateTable:
    description: ""
    aliases: [ crtb ]
    permissions: bingoPlg.create_table
    usage: "/CreateTable"

  StartBingo:
    description: ""
    aliases: [ sb ]
    permission: bingoPlg.start_bingo
    usage: "/StartBingo"

  SettingsClock:
    description: ""
    aliases: [ sc ]
    permission: bingoPlg.settings_clock
    usage: "/SettingsClock"

  permissions:
    bingoPlg.*:
      description: Gives access to all doorman commands
      children:
        bingoPlg.heal: op

        bingoPlg.delete_group: op
        bingoPlg.teleport_group: op

        bingoPlg.table: op
        bingoPlg.create_table: op

        bingoPlg.start_bingo: op

        bingoPlg.settings_clock: op