name: BingoPlg
version: '1.3.2'
main: me.dubovoy.bingoPlg.BingoPlg
api-version: '1.21'
authors: [ Dubovoy6211@gmail.com ]

commands:
  heal:
    description: "Heals player"
    aliases: [ h ]
    permissions: bingoPlg.heal
    usage: "/heal"

  CreateTeam:
    description: ""
    aliases: [ crtm ]
    usage: "/CreateTeam <Название вашей команды>"

  DeleteTeam:
    description: ""
    aliases: [ dltm ]
    permissions: bingoPlg.delete_team
    usage: "/DeleteTeam <Название команды>"

  JoinTeam:
    description: ""
    aliases: [ jt, join ]
    usage: "/JoinTeam <Название вашей команды>"

  TeleportTeam:
    description: ""
    aliases: [ tptm ]
    permissions: bingoPlg.teleport_team
    usage: "/TeleportTeam <Название команды>"

  Table:
    description: ""
    aliases: [ ]
    permissions: bingoPlg.table
    usage: "/Table 0"

  CreateTable:
    description: ""
    aliases: [ crtb ]
    permissions: bingoPlg.create_table
    usage: "/CreateTable"

  StartBingo:
    description: ""
    aliases: [ sb ]
    permission: bingoPlg.start_bingo
    usage: "/StartBingo"

  SettingsClock:
    description: ""
    aliases: [ sc ]
    permission: bingoPlg.settings_clock
    usage: "/SettingsClock"

  permissions:
    bingoPlg.*:
      description: Gives access to all doorman commands
      children:
        bingoPlg.heal: op

        bingoPlg.delete_team: op
        bingoPlg.teleport_team: op

        bingoPlg.table: op
        bingoPlg.create_table: op

        bingoPlg.start_bingo: op

        bingoPlg.settings_clock: op

#    bingoPlg.heal:
#      description: "Право для использования команды /heal"
#      default: op